### PR TITLE
Remove walrus operator for better Python 3.7 compatibility

### PR DESCRIPTION
**Pull request by encukou**
I haven't actually tested this with Python 3.7

### CODE REVIEW

**Comment by encukou** [comment]
@stratakis Does this help with https://github.com/fedora-python/cpython/pull/13#issuecomment-664446988 ?

**Comment by stratakis** [comment]
Indeed it works, thanks!

**Comment by stratakis** [comment]
Although not sure of the expected output, but here is a diff when applying it, with https://github.com/fedora-python/cpython/pull/13 and `python3 importpatches.py -f <my local branch>` on the python3.7 package: https://paste.centos.org/view/c9ffc2db

**Comment by encukou** [comment]
That looks right. The headers change to `0000000000000000000000000000000000000000` and Git versions are removed, so future diffs won't include them. Patch description are taken from the commit messages; a while back Miro went through them and put in the ones from the spec where they were better. And the patch headers in the spec include a patch ID, so it's easier to spot semantic differences.

**Comment by hroncok** [comment]
The diff looks good. (I suppose running importpatches first and adding the new patches in a sparate commit would make it more understandable, see for example https://src.fedoraproject.org/rpms/python3.9/pull-request/18#commit_list.)

**Pull request merged**
